######################################################################
# Automatically generated by qmake (2.01a) Thu Sep 23 18:08:25 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += opengl

# Input
HEADERS += cell.h GLWidget.h model.h solution.h
SOURCES += cell.cpp \
           GLWidget.cpp \
           main.cpp \
           model.cpp \
           ShallowWater.cpp \
           solution.cpp
